DEBUG = {}
DEBUG['main.PRINT_AST_BEFORE_UNIFY'] = False
DEBUG['typer.PRINT_CONSTRS'] = False
DEBUG['typer.PRINT_TVMAP'] = False
DEBUG['typer.PRINT_VARTY_AFTER_UNIFICATION'] = False
DEBUG['typer.PRINT_UNIF_STATS'] = False

